# -*- coding: utf-8 -*-
{
    'name': "Whatsapp Bot Responder",
    'version': '1.0',
    'category': '',
    'summary': """ Automatiza respuestas en WhatsApp mediante un bot sencillo """,
    'description': """ Este módulo permite automatizar respuestas en WhatsApp mediante un bot sencillo que responde a mensajes recibidos desde Odoo. """,
    'author': 'GonzaOdoo',
    'company': 'GonzaOdoo',
    'maintainer': 'GonzaOdoo',
    'website': '',
    'depends': ['whatsapp','helpdesk','website_helpdesk'],
    'data': [
        'views/whatsapp_bot_script_views.xml',
        'security/ir.model.access.csv',
        'views/whatsapp_bot_conversations.xml',
        'views/helpdesk_ticket.xml',
        'views/reclamos_views.xml',
        'views/consultas_views.xml',
        'views/secretaria_views.xml',
        'views/website_helpdesk_views.xml',
        'views/geo_barrio_views.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
